### ISSUE TITLE
Arm nil reference exception with "protocol not supported"

### ISSUE THREAD

**Issue by paralin** [vishvananda/netlink#148]
This is referencing this docker issue: https://github.com/docker/docker/issues/24018

On ARMv7 on an Odroid U3 with kernel version 4.6.3 

```
could not create netlink handle on initial namespace: protocol not supported
```

This results in a nil reference exception:

```
May 21 22:36:04 u3 systemd[1]: Starting Docker Application Container Engine...
May 21 22:36:04 u3 dockerd[5308]: time="2016-05-21T22:36:04.625731116Z" level=info msg="New containerd process, pid: 5323"
May 21 22:36:05 u3 dockerd[5308]: time="2016-05-21T22:36:05.711054324Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
May 21 22:36:05 u3 dockerd[5308]: time="2016-05-21T22:36:05.716723949Z" level=warning msg="mountpoint for pids not found"
May 21 22:36:05 u3 dockerd[5308]: time="2016-05-21T22:36:05.720063074Z" level=info msg="Loading containers: start."
May 21 22:36:05 u3 dockerd[5308]: time="2016-05-21T22:36:05.913945908Z" level=info msg="Firewalld running: false"
May 21 22:36:06 u3 dockerd[5308]: time="2016-05-21T22:36:06.081978699Z" level=error msg="could not create netlink handle on initial namespace: protocol not supported"
May 21 22:36:06 u3 dockerd[5308]: time="2016-05-21T22:36:06.087732533Z" level=error msg="could not create netlink handle on initial namespace: protocol not supported"
May 21 22:36:06 u3 dockerd[5308]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 22:36:06 u3 dockerd[5308]: [signal 0xb code=0x1 addr=0xc pc=0x989ff4]
May 21 22:36:06 u3 dockerd[5308]: goroutine 1 [running]:
May 21 22:36:06 u3 dockerd[5308]: panic(0x11e9158, 0x11e1e030)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/host/usr/lib/go/src/runtime/panic.go:481 +0x330
May 21 22:36:06 u3 dockerd[5308]: github.com/vishvananda/netlink.(*Handle).LinkByName(0x0, 0x1356aa8, 0x7, 0x0, 0x0, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/vendor/src/github.com/vishvananda/netlink/link_linux.go:759 +0x$8
May 21 22:36:06 u3 dockerd[5308]: github.com/docker/libnetwork/netutils.ElectInterfaceAddresses(0x1356aa8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/vendor/src/github.com/docker/libnetwork/netutils/utils_linux.go$78 +0xac
May 21 22:36:06 u3 dockerd[5308]: github.com/docker/docker/daemon.initBridgeDriver(0xb4dcbcf8, 0x11e85680, 0x120fc700, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/vendor/src/github.com/docker/docker/daemon/daemon_unix.go:712 +$x4c0
May 21 22:36:06 u3 dockerd[5308]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0x11e01ee0, 0x120fc700, 0x121787e0, 0x0, 0x0, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/vendor/src/github.com/docker/docker/daemon/daemon_unix.go:661 +$x5cc
May 21 22:36:06 u3 dockerd[5308]: github.com/docker/docker/daemon.(*Daemon).restore(0x11e01ee0, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/vendor/src/github.com/docker/docker/daemon/daemon.go:223 +0xc98
May 21 22:36:06 u3 dockerd[5308]: github.com/docker/docker/daemon.NewDaemon(0x120fc700, 0xb5f32628, 0x12005620, 0xb5f32458, 0x12106310, 0x0, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/vendor/src/github.com/docker/docker/daemon/daemon.go:596 +0x2aa$
May 21 22:36:06 u3 dockerd[5308]: main.(*DaemonCli).start(0x120f9de0, 0x0, 0x0)
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/cmd/dockerd/daemon.go:269 +0x165c
May 21 22:36:06 u3 dockerd[5308]: main.main()
May 21 22:36:06 u3 dockerd[5308]:         /skiff/workspaces/u/output/build/docker-engine-v1.12.0-rc2/cmd/dockerd/docker.go:68 +0x470
```

Specifically:

```
github.com/vishvananda/netlink.(*Handle).LinkByName
```

Any ideas if this is a bug with this library or Docker or something else?

**Comment by paralin** [comment]
Apparently fixed downstream

**Comment by aboch** [comment]
Yes @paralin thanks for closing

The issue you are facing is not really specific to netlink package, but  to the use libnetwork makes of its netlink.Handle, which fails to be created if the needed xfrm modules are missing on your machine.

It was fixed by https://github.com/docker/libnetwork/pull/1281, thanks to the addition of https://github.com/vishvananda/netlink/pull/143.  And brought to docker/docker via https://github.com/docker/docker/pull/23859.
