### ISSUE TITLE
Hang in Receive() on Linux

### ISSUE THREAD

**Issue by fasaxc** [vishvananda/netlink#254]
One of our users reported an issue (https://github.com/projectcalico/felix/issues/1522) where our application occasionally locks up.  After dumping a stack trace, we found this trace.  If I'm reading it correctly, it looks like Receive blocked for 66 minutes, which looks really suspicious:
```
goroutine 10672222 [syscall, 66 minutes]:
syscall.Syscall6(0x2d, 0x4, 0xc420d3e000, 0x1000, 0x0, 0xc420cb9268, 0xc420cb925c, 0x2b, 0x7f49c76b1a00, 0x450a40)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x4, 0xc420d3e000, 0x1000, 0x1000, 0x0, 0xc420cb9268, 0xc420cb925c, 0x0, 0xc420cb9294, 0xc42043ac00)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x99
syscall.Recvfrom(0x4, 0xc420d3e000, 0x1000, 0x1000, 0x0, 0x1000, 0x4, 0x200d600, 0xc420f4c3c0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:252 +0xaf
github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc420755260, 0xc49c9866d2, 0x0, 0x0, 0x0, 0x40eb82)
	/go/src/github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:613 +0x9b
github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute(0xc420137ae0, 0x0, 0x12f0000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:410 +0x181
github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink.execGetLink(0xc420137ae0, 0xc420de7160, 0x1, 0x1, 0x2)
	/go/src/github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/link_linux.go:1018 +0x3f
github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink.(*Handle).LinkByName(0x208ab20, 0xc420e24540, 0xf, 0x7f49c76eb000, 0x0, 0x407835, 0xc420cb9640)
	/go/src/github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/link_linux.go:958 +0x215
github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink.LinkByName(0xc420e24540, 0xf, 0x13656ad, 0xc420cb9658, 0xc420cb9650, 0xc420e9ad80)
	/go/src/github.com/projectcalico/felix/vendor/github.com/vishvananda/netlink/link_linux.go:941 +0x41
github.com/projectcalico/felix/routetable.realDataplane.LinkByName(0xc42000c1c0, 0xc420e24540, 0xf, 0xc420de7130, 0xc420755230, 0xc420137a00, 0x1)
	/go/src/github.com/projectcalico/felix/routetable/dataplane_shim.go:46 +0x35
github.com/projectcalico/felix/routetable.(*RouteTable).syncRoutesForLink(0xc4202c0620, 0xc420e24540, 0xf, 0x0, 0x0)
	/go/src/github.com/projectcalico/felix/routetable/route_table.go:258 +0x519
github.com/projectcalico/felix/routetable.(*RouteTable).Apply.func1(0x148f6c0, 0xc420e24c10, 0xc420cb9dd0, 0xc420498990)
	/go/src/github.com/projectcalico/felix/routetable/route_table.go:178 +0x112
github.com/projectcalico/felix/set.mapSet.Iter(0xc420bce540, 0xc420e24f20)
	/go/src/github.com/projectcalico/felix/set/set.go:101 +0xaf
github.com/projectcalico/felix/routetable.(*RouteTable).Apply(0xc4202c0620, 0x0, 0x0)
	/go/src/github.com/projectcalico/felix/routetable/route_table.go:200 +0xa4
github.com/projectcalico/felix/intdataplane.(*InternalDataplane).apply.func2(0xc420222f00, 0xc420930800, 0xc4202c0620)
	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:740 +0x2f
created by github.com/projectcalico/felix/intdataplane.(*InternalDataplane).apply
	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:746 +0x2fc
```
It looks like the Receive call has hung?

**Comment by fasaxc** [comment]
Should there be a timeout; my understanding is that netlink isn't reliable so it can drop packets.  Is there anything else I should look out for?

**Comment by aboch** [comment]
@fasaxc 

> Should there be a timeout

#170 allows the client to set the timeout in case it uses the netlink Handle structure.
If the client uses the netlink package API instead, no timeout is set.

**Comment by fasaxc** [comment]
I think #170 will do the trick for me.
