### ISSUE TITLE
`GenlFamilyList()`: `fatal error: checkptr: converted pointer straddles multiple allocations`

### ISSUE THREAD

**Issue by qdm12** [vishvananda/netlink#720]
There is a race issue in the `GenlFamilyList()` function.

Reproduction:

```go
package main

import (
	"testing"

	"github.com/vishvananda/netlink"
)

func Test(t *testing.T) {
	_, _ = netlink.GenlFamilyList()
}

```

And run the test with the race detector enabled:

```sh
CGO_ENABLED=1 go test -race -run ^Test$ .
```

(this is running on an Alpine host)

Gives logs

```
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 19 [running]:
runtime.throw({0x5c457a, 0x57bdc2})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc000052a30 sp=0xc000052a00 pc=0x466ff1
runtime.checkptrAlignment(0x18, 0x58f940, 0x57cf01)
        /usr/local/go/src/runtime/checkptr.go:26 +0x6c fp=0xc000052a50 sp=0xc000052a30 pc=0x438d6c
github.com/vishvananda/netlink/nl.(*Genlmsg).Serialize(0xc0000c046e)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20211129163951-9ada19101fc5/nl/genetlink_linux.go:88 +0x3b fp=0xc000052a78 sp=0xc000052a50 pc=0x57b9fb
github.com/vishvananda/netlink/nl.(*NetlinkRequest).Serialize(0xc0000a6190)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20211129163951-9ada19101fc5/nl/nl_linux.go:378 +0x382 fp=0xc000052b48 sp=0xc000052a78 pc=0x57bdc2
github.com/vishvananda/netlink/nl.(*NetlinkSocket).Send(0xc0000a0060, 0x50fa2c)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20211129163951-9ada19101fc5/nl/nl_linux.go:650 +0x54 fp=0xc000052bc0 sp=0xc000052b48 pc=0x57cfb4
github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute(0xc0000a6190, 0x0, 0x0)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20211129163951-9ada19101fc5/nl/nl_linux.go:446 +0x32a fp=0xc000052de0 sp=0xc000052bc0 pc=0x57c20a
github.com/vishvananda/netlink.(*Handle).GenlFamilyList(0xc000052e78)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20211129163951-9ada19101fc5/genetlink_linux.go:136 +0x1a5 fp=0xc000052e80 sp=0xc000052de0 pc=0x57ee05
github.com/vishvananda/netlink.GenlFamilyList(...)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20211129163951-9ada19101fc5/genetlink_linux.go:144
github.com/qdm12/gluetun.Test(0x0)
        /workspace/my_test.go:10 +0x37 fp=0xc000052e98 sp=0xc000052e80 pc=0x580fd7
testing.tRunner(0xc0000836c0, 0x5c5198)
        /usr/local/go/src/testing/testing.go:1259 +0x230 fp=0xc000052fb0 sp=0xc000052e98 pc=0x50fc10
testing.(*T).Run·dwrap·21()
        /usr/local/go/src/testing/testing.go:1306 +0x48 fp=0xc000052fe0 sp=0xc000052fb0 pc=0x5111a8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x4985e1
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x727

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000083520, {0x5ba6b4, 0x4}, 0x5c5198)
        /usr/local/go/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
        /usr/local/go/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc000083520, 0xc0000adbf8)
        /usr/local/go/src/testing/testing.go:1259 +0x230
testing.runTests(0xc0000d6000, {0x6d2040, 0x1, 0x1}, {0x0, 0x7fdf262eefff, 0x6daa00})
        /usr/local/go/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc0000d6000)
        /usr/local/go/src/testing/testing.go:1504 +0x9d2
main.main()
        _testmain.go:43 +0x22c
FAIL    github.com/qdm12/gluetun        0.006s
FAIL
```

**Comment by vishvananda** [comment]
Hmm, this method is using the same serialization that we do for all other netlink messages. Do you get the same error in any of the other tests?

**Comment by neiljerram** [comment]
FYI I'm also seeing this:
```
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 237 [running]:
runtime.throw({0x442eafe, 0x1f38610})
	/usr/local/go-cgo/src/runtime/panic.go:1198 +0x71 fp=0xc000e3f428 sp=0xc000e3f3f8 pc=0x4533f1
runtime.checkptrAlignment(0xc0009161c0, 0x8, 0x18)
	/usr/local/go-cgo/src/runtime/checkptr.go:26 +0x6c fp=0xc000e3f448 sp=0xc000e3f428 pc=0x42450c
github.com/vishvananda/netlink/nl.DeserializeRtNexthop(...)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/nl/route_linux.go:51
github.com/vishvananda/netlink.deserializeRoute.func1({0xc0009161c8, 0x10, 0x10})
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/route_linux.go:1137 +0x86 fp=0xc000e3f580 sp=0xc000e3f448 pc=0x1f38a26
github.com/vishvananda/netlink.deserializeRoute({_, _, _})
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/route_linux.go:1195 +0x18d0 fp=0xc000e3f908 sp=0xc000e3f580 pc=0x1f38610
github.com/vishvananda/netlink.routeSubscribeAt.func2()
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/route_linux.go:1484 +0x45b fp=0xc000e3ffe0 sp=0xc000e3f908 pc=0x1f3b8bb
runtime.goexit()
	/usr/local/go-cgo/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000e3ffe8 sp=0xc000e3ffe0 pc=0x4867a1
created by github.com/vishvananda/netlink.routeSubscribeAt
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/route_linux.go:1452 +0x436
```
