### ISSUE TITLE
Panic in DeserializeRtNexthop

### ISSUE THREAD

**Issue by fasaxc** [vishvananda/netlink#780]
Observed a panic in `DeserializeRtNexthop` in `route_linux.go` 
```
felix-0-6329-70-felixfv[stderr] goroutine 199 [running]:
felix-0-6329-70-felixfv[stderr] runtime.throw({0x4675c5f, 0x20fff70})
felix-0-6329-70-felixfv[stderr] 	/usr/local/go-cgo/src/runtime/panic.go:1198 +0x71 fp=0xc000b83400 sp=0xc000b833d0 pc=0x454d11
felix-0-6329-70-felixfv[stderr] runtime.checkptrAlignment(0xc0007762b0, 0x8, 0x18)
felix-0-6329-70-felixfv[stderr] 	/usr/local/go-cgo/src/runtime/checkptr.go:26 +0x6c fp=0xc000b83420 sp=0xc000b83400 pc=0x4247cc
felix-0-6329-70-felixfv[stderr] github.com/vishvananda/netlink/nl.DeserializeRtNexthop(...)
felix-0-6329-70-felixfv[stderr] 	/go/pkg/mod/github.com/vishvananda/netlink@v1.2.0-beta.0.20220404152918-5e915e014938/nl/route_linux.go:51
felix-0-6329-70-felixfv[stderr] github.com/vishvananda/netlink.deserializeRoute.func1({0xc0007762b8, 0x10, 0x10})
felix-0-6329-70-felixfv[stderr] 	/go/pkg/mod/github.com/vishvananda/netlink@v1.2.0-beta.0.20220404152918-5e915e014938/route_linux.go:1131 +0x86 fp=0xc000b83558 sp=0xc000b83420 pc=0x2100b06
```
At first glance, I think the problem is that this code: 
```
type RtNexthop struct {
	unix.RtNexthop
	Children []NetlinkRequestData
}

func DeserializeRtNexthop(b []byte) *RtNexthop {
	return (*RtNexthop)(unsafe.Pointer(&b[0:unix.SizeofRtNexthop][0]))
}
```
Slices `b` to `unix.SizeofRtNexthop` length but then it casts it to a pointer to a struct that is longer than that (due to the extra Children) field.  The runtime check that's failing is this:
```
	// Check that (*[n]elem)(p) doesn't straddle multiple heap objects.
	// TODO(mdempsky): Fix #46938 so we don't need to worry about overflow here.
	if checkptrStraddles(p, n*elem.size) {
		throw("checkptr: converted pointer straddles multiple allocations")
	}
```

**Comment by fasaxc** [comment]
I put up a fix in #781 PTAL.
