### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by udhos** [vishvananda/netlink#99]
I'm getting the go get error below:

```
lab@ubu10:~/devel$ go get github.com/vishvananda/netlink
# github.com/vishvananda/netlink
nexthop/src/github.com/vishvananda/netlink/bpf_linux.go: In function ‘load_simple_bpf’:
nexthop/src/github.com/vishvananda/netlink/bpf_linux.go:33:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   .insns = (__u64)&insns,
            ^
nexthop/src/github.com/vishvananda/netlink/bpf_linux.go:34:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   .license = (__u64)&license,
              ^
lab@ubu10:~/devel$
lab@ubu10:~/devel$ go version
go version go1.6 linux/386
lab@ubu10:~/devel$
```

**Comment by drzaeus77** [comment]
I will look into that, the fix shouldn't be too difficult. And is it a
warning like it said or does it fail to run afterwards.

**Comment by udhos** [comment]
> And is it a warning like it said or does it fail to run afterwards.

It seems to cause actual issues:

```
root@ubu10:/home/lab/devel# go test github.com/vishvananda/netlink
# github.com/vishvananda/netlink
nexthop/src/github.com/vishvananda/netlink/bpf_linux.go: In function ‘load_simple_bpf’:
nexthop/src/github.com/vishvananda/netlink/bpf_linux.go:33:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   .insns = (__u64)&insns,
            ^
nexthop/src/github.com/vishvananda/netlink/bpf_linux.go:34:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   .license = (__u64)&license,
              ^
--- FAIL: TestLinkAddDelGretap (0.08s)
        link_test.go:123: Link not removed properly
--- FAIL: TestXfrmPolicyAddDel (0.62s)
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 52 [running]:
panic(0x81fbac0, 0x1850a018)
        /usr/local/go/src/runtime/panic.go:464 +0x326
testing.tRunner.func1(0x1856be60)
        /usr/local/go/src/testing/testing.go:467 +0x14f
panic(0x81fbac0, 0x1850a018)
        /usr/local/go/src/runtime/panic.go:426 +0x3fd
github.com/vishvananda/netlink.XfrmPolicyList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/lab/devel/nexthop/src/github.com/vishvananda/netlink/xfrm_policy_linux.go:103 +0x754
github.com/vishvananda/netlink.TestXfrmPolicyAddDel(0x1856be60)
        /home/lab/devel/nexthop/src/github.com/vishvananda/netlink/xfrm_policy_test.go:29 +0x2e4
testing.tRunner(0x1856be60, 0x8300d4c)
        /usr/local/go/src/testing/testing.go:473 +0x8f
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:582 +0x6f2
FAIL    github.com/vishvananda/netlink  6.068s
root@ubu10:/home/lab/devel#
```

**Comment by drzaeus77** [comment]
Hmm, those seem like two different issues, the xfrm and gretap code paths
will not exercise bpf. The gcc build and warnings happens pretty early on,
before any tests start.

**Comment by drzaeus77** [comment]
I cannot reproduce the warning, which version of gcc is installed on the system?

Can you tell me if this makes the warning go away?:

```patch
diff --git a/bpf_linux.go b/bpf_linux.go
index 9b87ba4..faf9881 100644
--- a/bpf_linux.go
+++ b/bpf_linux.go
@@ -30,8 +30,8 @@ static int load_simple_bpf(int prog_type) {
        } __attribute__((aligned(8))) attr = {
                .prog_type = prog_type,
                .insn_cnt = 2,
-               .insns = (__u64)&insns,
-               .license = (__u64)&license,
+               .insns = (uintptr_t)&insns,
+               .license = (uintptr_t)&license,
        };
        return syscall(__NR_bpf, 5, &attr, sizeof(attr));
 #else
```

And, I doubt this will have any effect on the xfrm or gretap test failures. The xfrm seems to be the more serious of the two, but I don't know that code so can't speculate further.

**Comment by udhos** [comment]
> I cannot reproduce the warning, which version of gcc is installed on the system?

```
lab@ubu10:~$ go version
go version go1.6 linux/386
lab@ubu10:~$
lab@ubu10:~$ gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

lab@ubu10:~$
lab@ubu10:~$ uname -a
Linux ubu10 4.1.3-040103-generic #201507220129 SMP Wed Jul 22 01:40:10 UTC 2015 i686 i686 i686 GNU/Linux
lab@ubu10:~$
```

> Can you tell me if this makes the warning go away?:

It is yielding another fault:
```
/home/lab/devel/nexthop/src/github.com/udhos/netlink/bpf_linux.go:33:13: error: 'uintptr_t' undeclared (first use in this function)
   .insns = (uintptr_t)&insns,
```

**Comment by drzaeus77** [comment]
On my system the header defining uintptr_t is automatically included somewhere, but regardless I have just sent a pull request #100 that should work. I tested on ubuntu/wily32 in vagrant.
